services:
  bilibili-downloader:
    image: nbzzd6/bilibili-audio-downloader:latest-dev
    container_name: bilibili-downloader
    ports:
      - "5000:5000"  # Flask应用
      - "8765:8765"  # WebSocket服务器
    volumes:
      - ./downloads:/mnt/shares/audiobooks
      - ./templates:/app/templates  # 添加模板目录映射
      - ./static:/app/static        # 添加静态文件目录映射
    environment:
      - VIRTUAL_ENV=/opt/venv
      - PATH=/opt/venv/bin:$PATH
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - FLASK_APP=src.app:app
      - FLASK_DEBUG=1  # 添加调试模式
      - WS_HOST=0.0.0.0  # 添加WebSocket主机
      - WS_PORT=8765     # 添加WebSocket端口
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
