version: '3.8'

services:
  bilibili-downloader:
    image: nbzzd6/bilibili-audio-downloader:latest-dev
    container_name: bilibili-downloader
    ports:
      - "5000:5000"  # Flask应用
      - "8765:8765"  # WebSocket服务器
    volumes:
      - ./downloads:/mnt/shares/audiobooks
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
