version: '3.8'

services:
  web:
    image: nbzzd6/bilibili-audio-downloader:latest
    platform: linux/amd64  # 或者 linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ./path_to_your_volume:/mnt/shares/audiobooks  # 卷映射
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
